### ISSUE TITLE
UK Online Safety Act

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1267]
**Summary**
New targets and deadlines to hit 

**Outcome/deliverable**
Compliance with the below:

- [x] User safety should be prioritised and senior people should be held accountable
- [x] #1268
- [x] Offenders should not be able to share child sexual abuse content and children should be not be able to be contacted (unsafely)
- [x] Illegal content – including hate and terror – is to be taken down quickly
- [x] Women and girls should face less gendered harm and abuse online (including appropriate reporting channels)
- [x] Online fraud should be reduced
- [x] Users (especially children) should be empowered to have control over their online experience
- [x] More transparency on how platforms keep users safe
- [ ] Enforcement Priorities - Implications for Ocado 
- [x] #1269

**Deadline**
Various

**Links**
Link to doc: https://docs.google.com/document/d/12VbPZVN4E1rM2NHu0KL573HgyQI6LstvwTA0doEz1Is/edit?usp=sharing

**Reviewer**
Who should review this task?

**People to contact**
List the people that should/could be contacted before/during/after this task is done.
