### ISSUE TITLE
Kurono Asset and Story Creation

### ISSUE THREAD

**Issue by MMFernando** [ocadotechnology/codeforlife-admin#217]
## Description 
Create 2D and 3D assets for Kurono, as well as story snippets.

## Checklist
- [x] General narrative snippet
- [x] Narrative snippet for each timeline/challenge
- [x] 3 character designs
- [x] 3 character descriptions
- [x] 3 character models + textures 
- [x] 5 background designs
- [x] 5 terrain textures
- [x] 5 obstacle models + textures
- [ ] 3 artefact designs x 5 timelines
- [x] 3 artefact models + textures x 5 timelines
- [ ] one-line descriptions for each artefact

**Comment by lauracumming** [comment]
Closing as completed
