### ISSUE TITLE
Data tracking for restructure

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#754]
Design and set up  a measurable way to track our progress with the restructure. Our KPI is to reduce development time by 10%. We would like to assign a task that we can complete now and then complete again in 9 months time to see if we have managed to hit our target.

- [ ] Design task that can be repeated
- [ ] Complete tasks and track timings
- [ ] Add to a dashboard (Saucelabs?)
