### ISSUE TITLE
Data mining - Kurono

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#796]
- [x] Returning classes - classes that use more than 1 worksheet
- [x] Badges collected - worksheet 1
- [x] Game load time

## Returning classes

What I (Florian) said in the sprint planning of 18/10/23 was wrong - changing worksheets does not create a new Game object in the DB which makes it harder to track worksheet changes or "returning classes".
We would probably need to add a tracker somewhere on the DB (either at the class level, or in the DailyActivity table).
Philosophical question: how do we / can we differentiate between when a class is actually trying out a new worksheet and when a teacher is just testing worksheets by themselves? Potential answer: should we say that worksheet change + socket connections from the actual students in the class (ie, not just the teacher) = class is actually using the new worksheet?

## Badges collected

Each User has info about the badges collected on their UserProfile.
What do we want to track in relation to this? Just total number of earned badges? Earned badges over time (we don't have that setup)?

## Game load time

We need to agree on "load time".

Proposed definition:
- Start time = when any user clicks the "Play" button
- End time = when the user's avatar manages to perform their first turn
- Load time = End time - Start time

The logic relating to loading a game mainly happens in the aimmo-game Docker image. While the clicking of the "Play" button (which triggers the `watch_game` endpoint is on the Django side, everything else happens in the game image. Will this be a problem? How to communicate the load time back to the DB in Django? Where do we store the load time - is it tied to a User?

**Comment by lauracumming** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Code-for-Life-Admin-5cf7f1b750c6a6242c50af4c/issues/ocadotechnology/codeforlife-admin/796?planning-poker) with Zenhub @faucomte97 @SKairinos

**Comment by SKairinos** [comment]
@lauracumming , I thought we had this data available to us. I discovered that its not and we first need to make this an epic on the dev board so we can gather all this data. Then, we can query and present it in LS. Should we address this next sprint?

**Comment by lauracumming** [comment]
Hi @SKairinos this is an epic for that reason. But we should be doing these tasks in this sprint and should've caught this when exploring what needed to be done for the task. Let's ensure that BQ is checked when looking at and estimating tasks to understand what is available.

**Comment by SKairinos** [comment]
I have created [this epic](https://app.zenhub.com/workspaces/code-for-life-development--56f2afba6e54555c586f6db3/issues/gh/ocadotechnology/aimmo/1824) on dev board to collect the required data

**Comment by lauracumming** [comment]
Hey @SKairinos  Just checking - Is this ever created? But we will need the data to build up?

**Comment by SKairinos** [comment]
the data is currently being collected and reported [here](https://lookerstudio.google.com/reporting/66482b38-4a70-422a-9099-9ccda493bc65/page/p_edrnf45qqc/edit)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0x1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--767da47234f416afd79fde2551ba3a9381726218/image.png)

**Comment by lauracumming** [comment]
To clarify, I was asking, are these results, games 'ever created', or games created between a certain time, ie 28 days?

**Comment by SKairinos** [comment]
Sorry, misunderstood the question. Yes, these are all records ever created (there's no date range filter). There are few records because we only started collecting this data from last week so it'll need to build up.

**Comment by lauracumming** [comment]
Great. Okay. This is completed then. 👍
